server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/message/test
#        - id: consumerModule
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/consumer/**
